### ISSUE TITLE
[ERROR] Failed to execute goal on project differ-app: Could not resolve dependencies for project cz.nkp:differ-app:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.lizardtech:javadjvu-lib:jar:0.8.9-RELEASE, net.java.dev.jai-imageio:j

### ISSUE THREAD

**Issue by jstavel** [xrosecky/differ#1]
stavel@ntbstavel:/opt/differ/differ-webapp$ mvn install
 ends with error:

[ERROR] Failed to execute goal on project differ-app: Could not resolve dependencies for project cz.nkp:differ-app:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.lizardtech:javadjvu-lib:jar:0.8.9-RELEASE, net.java.dev.jai-imageio:jai-imageio-core-standalone:jar:1.2-pre-dr-b04-2010-04-30: Could not find artifact com.lizardtech:javadjvu-lib:jar:0.8.9-RELEASE in vaadin-addons (http://maven.vaadin.com/vaadin-addons) -> [Help 1]

Could you help me how to solve dependencies?

Regards,
Jan Stavel

**Comment by xrosecky** [comment]
Library javadjvu-lib-0.8.9-RELEASE.jar is not available in any maven repository, so it must be installed manually by executing this command:

mvn install:install-file -DgroupId=com.lizardtech -DartifactId=javadjvu-lib -Dversion=0.8.9-RELEASE -Dpackaging=jar -Dfile=javadjvu-lib-0.8.9-RELEASE.jar

Library javadjvu-lib-0.8.9-RELEASE.jar is available here:
https://github.com/xrosecky/differ/blob/master/javadjvu-lib-0.8.9-RELEASE.jar?raw=true
